string           uid                    # <class 'str'> V
NetDevice        dev_id                 # <enum 'NetDevice'> D1
Command          cmd_type               # <class 'eci.primitives.command.Command'> CMD
MessageID        msg_id                 # <enum 'MessageID'> caDirectControl
uint8            data_len               # <class 'int'> 
uint8            command                # <class 'int'> 
Percentage       speed                  # <class 'eci.primitives.percentage.Percentage'> 0
# Copyright © 2024 Covvi